services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_password
      POSTGRES_DB: mlflow_db
    ports:
      - "5444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: python:3.10-slim
    ports:
      - "5001:5000"  
    command: >
      bash -c "pip install mlflow psycopg2-binary &&
      mlflow server
      --backend-store-uri postgresql://mlflow_user:mlflow_password@db:5432/mlflow_db
      --default-artifact-root mlflow-artifacts:/
      --artifacts-destination /mlflow_artifacts
      --serve-artifacts
      --host 0.0.0.0"
    volumes:
      - ./local_artifacts:/mlflow_artifacts
    depends_on:
      - db

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"  
    depends_on:
      - db

  localstack:
    image: localstack/localstack:3.7.2
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data: